const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const OUT=path.resolve(process.env.TEST_OUT||'docs/verification/T03'),URL=process.env.TEST_URL||'http://127.0.0.1:8086';
fs.mkdirSync(OUT,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));page.setDefaultTimeout(10000);
 const openFor=async selector=>{const menu=page.locator(selector).locator('xpath=ancestor::details');if(await menu.count()&&!await menu.evaluate(e=>e.open))await menu.locator('summary').click();};
 const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('floorplan-project-v2')));
 const bytes=()=>page.evaluate(()=>localStorage.getItem('floorplan-project-v2'));
 const check=s=>{checks.push(s);console.log('PASS',s)};
 const fill=async fields=>{for(const [k,v] of Object.entries(fields))await page.locator(`#roomDialog [name=${k}]`).fill(v)};
 const apply=async()=>{await page.locator('#roomDialog [type=submit]').click();await page.waitForFunction(()=>!document.querySelector('#roomDialog').open)};
 const units=async m=>{await openFor('#projectUnits');await page.locator('#projectUnits').selectOption(m)};
 const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
 const field=async(id,v)=>{await page.locator('#'+id).fill(v);await page.locator('#'+id).press('Enter')};
 const download=async(id,name)=>{const pending=page.waitForEvent('download');await page.locator('details.menu summary').click();await page.locator('#'+id).click();const file=path.join(OUT,name);await(await pending).saveAs(file);return file};
 const mode=async m=>{await page.locator(`[data-view="${m}"]`).click();await page.waitForFunction(m=>!document.body.classList.contains('busy')&&document.body.classList.contains('m3d')===(m==='3d'),m,{timeout:45000})};
 try{
 await page.goto(URL);await page.locator('#gFurn [data-fid]').nth(45).waitFor();
 await units('imperial');const sample=await saved();
 await openFor('#newRoom');await page.locator('#newRoom').click();assert.equal(await page.locator('#projectUnits').isDisabled(),true);
 await fill({name:'T03 room',width:'12 ft',depth:'10 ft',height:'8 ft'});await apply();
 let p=await saved();assert.equal(p.units.display,'imperial');near(p.roomEditor.width,3657.6);near(p.roomEditor.depth,3048);near(p.roomEditor.height,2438.4);assert.match(await page.locator('#subtitle').textContent(),/120.00 sq ft/);assert.match(await page.locator('#gDims').textContent(),/12' 0"/);
 assert.equal(await page.locator('#grid').getAttribute('width'),'304.8');check('imperial inherited by new 12ft x 10ft x 8ft room; 120 sq ft, dimensions, grid');
 let stable=await bytes();await page.locator('#editRoom').click();await page.locator('[data-room-edit]').click();await apply();assert.equal(await bytes(),stable);
 await page.locator('#editRoom').click();await page.locator('[data-room-edit]').click();await fill({width:"5'12\""});await page.locator('#roomDialog [type=submit]').click();assert.equal(await bytes(),stable);assert.match(await page.locator('#width-feedback').textContent(),/72 in/);await page.keyboard.press('Escape');assert.equal(await page.locator('#projectUnits').isDisabled(),false);
 check('unchanged form no-op; strict combined inches error; unit lock and Escape');
 await page.locator('#editRoom').click();await page.locator('[data-add=door]').click();await fill({offset:'20 in',width:'30 1/2 in',height:'80 in'});await apply();
 const doorId=(await saved()).roomEditor.openings[0].id;near((await saved()).geometry.doors[0].len,774.7);
 await page.locator('#editRoom').click();await page.locator('#parentWall').selectOption('right');await page.locator('[data-add=window]').click();await fill({offset:'30 in',width:'40 in',height:'40 in',sill:'30 in'});await apply();
 p=await saved();const oldOpening=p.roomEditor.openings[0];await page.locator('#editRoom').click();await page.locator(`[data-edit="${doorId}"]`).click();await page.locator('[name=hinge]').selectOption('end');await apply();assert.deepEqual({...((await saved()).roomEditor.openings[0]),hinge:oldOpening.hinge},oldOpening);
 await page.locator('#lib .item').first().click();await field('fW','60 in');await field('fD','80 in');await field('fX',"-0' 6.5\"");await field('fY','1234.567891 mm');p=await saved();near(p.furniture[0].w,1524);near(p.furniture[0].d,2032);near(p.furniture[0].cx,-165.1);
 const furniture=p.furniture[0];await page.locator('#fName').fill('Fraction bed');await page.locator('#fName').press('Tab');assert.deepEqual({...((await saved()).furniture[0]),name:furniture.name},furniture);
 stable=await bytes();await page.locator('#fX').focus();await page.locator('#fX').press('Tab');assert.equal(await bytes(),stable);
 await page.locator('#fW').fill('1/3 in');await page.locator('#fW').press('Tab');assert.equal(await bytes(),stable);assert.equal(await page.locator('#fW').getAttribute('aria-invalid'),'true');for(const invalid of ['-3 in','0','49 mm','10000001 mm']){await page.locator('#fW').fill(invalid);await page.locator('#fW').press('Tab');assert.equal(await bytes(),stable);assert.equal(await page.locator('#fW').getAttribute('aria-invalid'),'true');}await page.locator('#fW').focus();await page.keyboard.press('Escape');assert.equal(await bytes(),stable);
 await field('fX','60 in');await field('fY','60 in');check('door fractions, hinge-only preservation, furniture 60x80in, signed coordinates, name-only and invalid field isolation');
 // Exact state equality through UI switches and ordered history.
 p=await saved();for(let i=0;i<100;i++)await units(i%2?'imperial':'metric');const after=await saved();assert.deepEqual({...after,updatedAt:p.updatedAt},p);
 await field('fW','60 1/64 in');const precise=await saved();await units('metric');await page.locator('#undo').click();assert.equal((await saved()).units.display,'imperial');await page.locator('#undo').click();near((await saved()).furniture[0].w,1524);await page.locator('#redo').click();await page.locator('#redo').click();near((await saved()).furniture[0].w,precise.furniture[0].w);await units('imperial');
 assert.match(await page.locator('#lib .item small').first().textContent(),/in/);assert.match(await page.locator('#sbText').textContent(),/'|in/);check('100 UI unit changes preserve all model values; fine input and ordered undo/redo');
 await page.locator('#plan').click({position:{x:20,y:200}});await page.locator('#gFurn [data-fid]').first().click();
 let before=(await saved()).furniture[0];await page.keyboard.press('ArrowRight');near((await saved()).furniture[0].cx-before.cx,6.35);await page.keyboard.press('Shift+ArrowDown');near((await saved()).furniture[0].cy-before.cy,25.4);await page.locator('#undo').click();await page.locator('#undo').click();
 // Real SVG mouse drag / resize / cancellation and measurement.
 const point=async(x,y)=>page.evaluate(({x,y})=>{const s=document.querySelector('#plan'),p=s.createSVGPoint();p.x=x;p.y=y;const q=p.matrixTransform(s.getScreenCTM());return{x:q.x,y:q.y}},{x,y});
 await openFor('[data-layer=wallSnap]');await page.locator('[data-layer=wallSnap]').click();before=(await saved()).furniture[0];let q=await point(before.cx,before.cy);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+35,q.y+15,{steps:5});await page.mouse.up();p=await saved();near(p.furniture[0].cx/6.35,Math.round(p.furniture[0].cx/6.35));await page.locator('#undo').click();assert.deepEqual((await saved()).furniture[0],before);
 q=await point(before.cx,before.cy);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+30,q.y+10,{steps:5});await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await saved()).furniture[0],before);
 await page.locator('#plan').evaluate(el=>el.addEventListener('pointerdown',e=>el.dataset.testPointer=e.pointerId,{once:true}));
 q=await point(before.cx,before.cy);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+30,q.y+10,{steps:5});
 await page.locator('#plan').evaluate(el=>el.dispatchEvent(new PointerEvent('pointercancel',{pointerId:Number(el.dataset.testPointer),bubbles:true})));await page.mouse.up();assert.deepEqual((await saved()).furniture[0],before);
 q=await point(before.cx,before.cy);await page.mouse.move(q.x,q.y);await page.mouse.down();await page.mouse.move(q.x+25,q.y+10,{steps:5});
 await page.locator('[data-view="3d"]').evaluate(button=>button.click());await page.waitForFunction(()=>!document.body.classList.contains('busy')&&document.body.classList.contains('m3d'),null,{timeout:45000});await page.mouse.up();assert.deepEqual((await saved()).furniture[0],before);await mode('2d');
 // View state updates before its CSS transition finishes; wait before screen-coordinate gestures.
 await page.locator('.app').evaluate(el=>Promise.all(el.getAnimations({subtree:true}).filter(a=>a.effect?.getComputedTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));
 let handle=await page.locator('#gSel rect[data-handle=size]').boundingBox();
 assert.equal(await page.evaluate(({x,y})=>document.elementFromPoint(x,y)?.getAttribute('data-handle'),{x:handle.x+handle.width/2,y:handle.y+handle.height/2}),'size','resize gesture must hit the actual handle');await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+handle.width/2+20,handle.y+handle.height/2+20,{steps:5});await page.mouse.up();p=await saved();near(p.furniture[0].w/6.35,Math.round(p.furniture[0].w/6.35));await page.locator('#undo').click();
 await page.locator('[data-tool=measure]').click();q=await point(200,200);await page.mouse.click(q.x,q.y);q=await point(1200,200);await page.mouse.click(q.x,q.y);assert.equal((await saved()).measures.length,1);assert.match(await page.locator('#gMeasure').textContent(),/'/);await page.locator('[data-tool=select]').click();check('imperial keyboard normal/Shift, SVG drag/resize/undo, Escape/pointercancel/view-switch cancellation and saved measurement');
 await page.screenshot({path:path.join(OUT,'imperial-2d.png')});
 const exported=await download('exportJson','imperial-project.json'),original=JSON.parse(fs.readFileSync(exported));assert.equal(original.units.display,'imperial');
 const png=await download('exportPng','imperial-2d.png.download.png');assert.equal(fs.readFileSync(png).subarray(1,4).toString(),'PNG');
 await page.reload();await page.locator('#gFurn [data-fid]').first().waitFor();assert.deepEqual(await saved(),original);
 await page.setInputFiles('#fileIn',exported);assert.deepEqual(await saved(),original);check('real JSON and PNG downloads; saved imperial refresh and actual file upload preserve mm');
 await mode('3d');await page.waitForTimeout(900);assert.match(await page.locator('#roomList').textContent(),/120.00 sq ft/);
 const canvas=await page.locator('#view3d canvas').evaluate(c=>c.toDataURL());await units('metric');await page.waitForTimeout(150);assert.equal(await page.locator('#view3d canvas').evaluate(c=>c.toDataURL()),canvas);assert.match(await page.locator('#roomList').textContent(),/m²/);await units('imperial');await page.screenshot({path:path.join(OUT,'imperial-3d.png')});check('real WebGL unit updates room list and labels; exact canvas pixels unchanged');
 await mode('2d');await openFor('#langBtn');await page.locator('#langBtn').click();assert.equal(await page.locator('#projectUnits').inputValue(),'imperial');await page.setViewportSize({width:390,height:844});await openFor('#newRoom');await page.locator('#newRoom').click();await fill({width:'5-6'});await page.locator('#roomDialog [type=submit]').click();await page.screenshot({path:path.join(OUT,'narrow-error.png')});await page.keyboard.press('Escape');await openFor('#projectUnits');assert.equal(await page.locator('#projectUnits').isVisible(),true);check('English language is independent; 390px unit control, dialog and localized field error');
 const legacy={furniture:sample.furniture,rooms:sample.rooms,demolished:sample.demolished,measures:sample.measures,units:sample.units};
 page.once('dialog',d=>d.accept());const backup=page.waitForEvent('download');
 await page.setInputFiles('#fileIn',{name:'legacy-imperial.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await(await backup).saveAs(path.join(OUT,'legacy-imperial-backup.json'));
 await page.waitForFunction(()=>document.querySelectorAll('#gFurn [data-fid]').length===46);assert.equal((await saved()).units.display,'imperial');assert.deepEqual((await saved()).furniture,sample.furniture);
 const v1=JSON.parse(fs.readFileSync('tests/fixtures/custom-project.json'));v1.units.display='imperial';await page.setInputFiles('#fileIn',{name:'v1-imperial.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(v1))});await page.waitForFunction(()=>document.querySelectorAll('#gRooms .room').length===1);assert.equal((await saved()).units.display,'imperial');assert.deepEqual((await saved()).furniture,v1.furniture);check('actual legacy backup/import and v1 migration retain existing imperial and millimetres');
 assert.deepEqual(errors,[]);fs.writeFileSync(path.join(OUT,'browser-results.json'),JSON.stringify({date:new Date().toISOString(),browser:browser.version(),checks,errors,sampleFurniture:sample.furniture.length},null,2));
 }catch(e){await page.screenshot({path:path.join(OUT,'failure.png')});throw e}finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
