const output=file=>(process.env.NA_TEST_OUT||'docs/verification/NA-fixes')+'/'+file;
export async function run({page,assert,project,context,fs,baseURL}){
 await page.locator('#fileIn').setInputFiles(output('NA-002-project.json'));await page.waitForFunction(()=>document.querySelectorAll('#gRooms polygon').length===3);let p=await project();assert(p.referencePlan?.visible,'house reference not restored');const bedroom=p.roomEditor.rooms[1].id;
 await page.locator('#editRoom').click();await page.locator('#activeRoom').selectOption(bedroom);await page.locator('#hideRoomLabel').check();await page.locator('[data-room-edit]').click();await page.locator('#roomDialog [name=name]').fill('Bedroom revised');await page.locator('#roomDialog [type=submit]').click();assert((await project()).rooms[bedroom].labelHidden,'room edit lost label preference');assert((await project()).name===p.name,'room edit renamed project');
 await page.locator('#parentWall').selectOption('left');await page.locator('[data-add=window]').click();await page.locator('#roomDialog [name=height]').fill('24 in');await page.locator('#roomDialog [type=submit]').click();await page.waitForSelector('#roomDialog',{state:'hidden'});assert((await project()).roomEditor.openings.at(-1).roomId===bedroom,'multi-room opening parent wrong');
 const before=JSON.stringify((await project()).geometry);await page.locator('[data-add=door]').click();await page.locator('#roomDialog [name=width]').fill('1000 ft');await page.locator('#roomDialog [type=submit]').click();assert(JSON.stringify((await project()).geometry)===before,'invalid opening mutated project');await page.locator('#roomDialog [data-cancel]').click();
 const dl=page.waitForEvent('download');await page.locator('#exportJson').evaluate(b=>b.click());await (await dl).saveAs(output('integration-house.json'));await page.reload();await page.waitForSelector('#gReference image');assert((await project()).rooms[bedroom].labelHidden,'restore lost room prefs');
 await page.locator('[data-view="3d"]').click();await page.waitForFunction(()=>document.querySelector('#stage').classList.contains('is3d')&&!document.body.classList.contains('busy'),{},{timeout:60000});await page.screenshot({path:output('integration-house-3D.png')});await page.locator('[data-view="2d"]').click();await page.waitForFunction(()=>!document.body.classList.contains('busy'));
 // PNG source is re-rasterized; it never imports project JSON or executes content.
 await page.locator('#drawingIn').setInputFiles(output('NA-007-export.png'));await page.waitForFunction(()=>document.querySelector('#referenceDialog canvas')?.width>500);const canvas=page.locator('#referenceDialog canvas'),box=await canvas.boundingBox();await canvas.click({position:{x:box.width*.2,y:box.height*.2}});await canvas.click({position:{x:box.width*.8,y:box.height*.2}});await page.locator('#referenceDistance').fill('20 ft');await page.locator('[data-apply]').click();await page.waitForSelector('#referenceDialog',{state:'hidden'});assert((await project()).referencePlan.name.endsWith('.png'),'PNG reference missing');
 await page.locator('#editRoom').click();await page.locator('#activeRoom').selectOption(bedroom);await page.locator('[data-room-delete]').click();assert((await project()).geometry.rooms.length===2,'delete room failed');assert(!(await project()).roomEditor.openings.some(o=>o.roomId===bedroom),'deleted room kept its openings');await page.locator('#undo').click();assert((await project()).geometry.rooms.length===3,'undo room deletion failed');
 const preserved=JSON.stringify(await project());page.once('dialog',d=>d.dismiss());await page.locator('#fileIn').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForTimeout(200);assert(JSON.stringify(await project())===preserved,'bad import changed data');
 await page.setViewportSize({width:390,height:844});await page.locator('#tgPanel').click();const units=await page.locator('#projectUnits').boundingBox();assert(units.x>=0&&units.x+units.width<=390,'mobile units clipped');await page.screenshot({path:output('integration-mobile.png')});await page.setViewportSize({width:1440,height:1000});
 const live=await context.browser().newContext(),livePage=await live.newPage();try{livePage.setDefaultTimeout(15000);const liveErrors=[];livePage.on('pageerror',e=>liveErrors.push(e.message));await livePage.goto('http://127.0.0.1:8086/');await livePage.reload();try{await livePage.waitForSelector('#lib .item',{state:'attached'});}catch(error){console.log('8086 boot errors:',liveErrors);throw error;}assert(!liveErrors.length,liveErrors.join('; '));const version=await livePage.locator('html').getAttribute('data-build');assert(version===await page.locator('html').getAttribute('data-build'),'original 8086 serves another version');}finally{await live.close();}
}
