const output=file=>(process.env.NA_TEST_OUT||'docs/verification/NA-fixes')+'/'+file;
export async function run({page,context,assert,project,fs}){
 await page.locator('#fileName').evaluate(e=>{e.value='House Alpha';e.dispatchEvent(new Event('change',{bubbles:true}));});await page.locator('#layoutName').evaluate(e=>{e.value='Layout B';e.dispatchEvent(new Event('change',{bubbles:true}));});
 const downloads=[];for(const [id,ext]of [['exportJson','json'],['exportPng','png']]){const pending=page.waitForEvent('download');await page.locator('#'+id).evaluate(b=>b.click());const d=await pending;assert(d.suggestedFilename().includes('House Alpha-Layout B-'),'project/layout filename missing');await d.saveAs(output('NA-012-')+(ext==='json'?'project':'2D')+'.'+ext);downloads.push(d.suggestedFilename());}
 await page.locator('#layoutName').evaluate(e=>{e.value='Layout C';e.dispatchEvent(new Event('change',{bubbles:true}));});const pending=page.waitForEvent('download');await page.locator('#exportJson').evaluate(b=>b.click());const next=await pending;assert(!downloads.includes(next.suggestedFilename()),'layout files indistinguishable');downloads.push(next.suggestedFilename());
 await page.locator('header details.menu').evaluate(d=>d.open=true);await page.locator('#printScale').selectOption('100');const popupEvent=page.waitForEvent('popup');await page.locator('#printPlan').evaluate(b=>b.click());const popup=await popupEvent;await popup.waitForLoadState();await popup.emulateMedia({media:'print'});await popup.pdf({path:output('NA-012-print-100.pdf'),preferCSSPageSize:true,printBackground:true});assert(await popup.locator('.ruler').evaluate(e=>Math.abs(e.getBoundingClientRect().width-100/25.4*96)<.1),'physical ruler is not 100 mm');await popup.close();console.log('print PDF complete');
 await page.locator('header details.menu').evaluate(d=>d.open=true);await page.locator('#exportView').selectOption('3d');const shot=page.waitForEvent('download',{timeout:60000});await page.locator('#exportPng').evaluate(b=>b.click());const d=await shot;assert(d.suggestedFilename().endsWith('3D.png'),'3D filename incorrect');await d.saveAs(output('NA-012-3D.png'));downloads.push(d.suggestedFilename());fs.writeFileSync(output('NA-012-downloads.json'),JSON.stringify(downloads,null,2));
 await page.locator('[data-view="2d"]').click();await page.waitForFunction(()=>!document.body.classList.contains('busy'));
}
